Session 2
yumemi-inc/ios-training-komori pull request #2
Opened 2023-12-20 04:27 UTC by MasahiroLittleforest

## 修正内容
[Session 2](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/API.md)の実装

- リロードボタン押下で天気を読み込み
- 天気が更新されたらUIに反映

## スクリーンショット
https://github.com/yumemi-inc/ios-training-komori/assets/50921804/aefb0960-b33e-4964-80ad-3c5691eab230

2023-12-20 07:55 UTC, novr requested changes

2023-12-20 07:55 UTC, novr commented on ios-training-komori/Assets.xcassets/img_cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
[must] Vecor画像なので、Preserve Vector DataにチェックをつけてSingle Scaleにしましょう

2023-12-20 07:55 UTC, novr commented on ios-training-komori/Model/WeatherModel.swift
> +    case rainy = "rainy"
[nits] rawValueの指定不要です
enum: Stringは、rawValueを再定義しなくてもcase名がそのままrawValueになるため

2023-12-20 07:55 UTC, novr commented on ios-training-komori/View/Weather/WeatherViewController.swift
> +            weatherImage.image = UIImage(named:"img_sunny")?.withRenderingMode(.alwaysTemplate)
[nits] Assets側の設定でalwaysTemplateを指定することも可能です

2023-12-20 07:58 UTC, novr commented on ios-training-komori/Model/WeatherModel.swift
> +    @Published var condition: WeatherCondition?
[imo] private(set)をつけるとconditionの書き換えをModel内に隠蔽できます

2023-12-20 08:23 UTC, MasahiroLittleforest commented on ios-training-komori/Assets.xcassets/img_cloudy.imageset/Contents.json
> +      "filename" : "iconmonstr-weather-11.pdf",
こちらで修正しました！ fd23ffa

2023-12-20 08:30 UTC, MasahiroLittleforest commented on ios-training-komori/Model/WeatherModel.swift
> +    case rainy = "rainy"
ありがとうございます！
Stringからenumに変換したい場合はこのような定義が要ると勘違いしていました。
case名と異なる場合rawValueにしたい場合は必要ということですね。
こちらで修正しました。 6b94ce2

2023-12-20 08:33 UTC, MasahiroLittleforest commented on ios-training-komori/View/Weather/WeatherViewController.swift
> +            weatherImage.image = UIImage(named:"img_sunny")?.withRenderingMode(.alwaysTemplate)
ViewController側で操作するたびに `withRenderingMode(.alwaysTemplate)` を呼ぶのは面倒なので修正しました。 855f193

2023-12-20 08:33 UTC, MasahiroLittleforest commented on ios-training-komori/Model/WeatherModel.swift
> +    @Published var condition: WeatherCondition?
修正しました！ 211c6c2

2023-12-20 14:24 UTC, ykws approved these changes
Vector 画像の対応ができているので LGTM 👍 
Combine の扱いも 💯 

細かい箇所コメントしていますが、いずれも Must ではないです。

2023-12-20 14:24 UTC, ykws commented on ios-training-komori/View/Weather/WeatherViewController.swift
> +    @IBOutlet weak var weatherImage: UIImageView!
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

iOS 16.4 から `@ViewLoading` という Property Wrapper が用意されたので、オプショナルを外すことができます

https://developer.apple.com/documentation/uikit/uiviewcontroller/viewloading
https://zenn.dev/yumemi_inc/articles/viewloading-property

```suggestion
    @IBOutlet @ViewLoading var weatherImage: UIImageView
```

2023-12-20 14:24 UTC, ykws commented on ios-training-komori/View/Weather/WeatherViewController.swift
> +    private var cancellables = Set<AnyCancellable>()
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

ここも型に命名が引きずられてしまっています。（コード例でよく見かける命名なのでその影響が大きいと感じています）
`cancellables` はスペルミス扱いになるのと、キャンセル可能なものではありますが、用途としては購読なので `subscriptions` 辺りも命名の候補として有力だと思っています。

```suggestion
    private var subscriptions = Set<AnyCancellable>()
```

2023-12-21 03:59 UTC, MasahiroLittleforest commented
@ykws 
>細かい箇所コメントしていますが、いずれも Must ではないです。

Approveしていただいているので、次のSessionにて修正しようと思います！

2023-12-21 04:45 UTC, novr approved these changes

2023-12-21 05:25 UTC, MasahiroLittleforest commented
レビューありがとうございました！
こちらマージします。

2023-12-21 05:25 UTC, merged