Session 6: Lifecycle
yumemi-inc/ios-training-komori pull request #6
Opened 2024-01-18 05:30 UTC by MasahiroLittleforest

[Session 6: Lifecycle](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/VC_Lifecycle.md)の実装です。

## 修正内容
- 最初の画面（FirstViewController）を作成
- 最初の画面が表示されたら天気予報画面を表示
- 天気予報画面の閉じるボタンを押下で最初の画面に戻る

## スクリーンショット
<img src="https://github.com/yumemi-inc/ios-training-komori/assets/50921804/1d868725-b2b0-45eb-abd2-57f58fc0feea" height="600" />

2024-01-20 00:25 UTC, ykws approved these changes
LGTM 👍

2024-01-20 00:25 UTC, ykws commented on ios-training-komori/View/Weather/Base.lproj/WeatherScreen.storyboard
> +                        <segue destination="BYZ-38-t0r" kind="show" identifier="navigateToWeatherViewController" id="ndx-rK-M9Z"/>
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)

2024-01-22 01:11 UTC, macneko-ayu commented on ios-training-komori/View/Weather/FirstViewController.swift
> +        performSegue(withIdentifier: "navigateToWeatherViewController", sender: nil)
![must-badge](https://img.shields.io/badge/review-must-red.svg)
override したライフサイクル系のメソッドは、意図しない動作をする可能性があるので super も必ず呼ぶようにしてください。
```suggestion
        super.viewDidAppear(animated)
        performSegue(withIdentifier: "navigateToWeatherViewController", sender: nil)
```

2024-01-22 01:12 UTC, macneko-ayu requested changes
一点コメントしました

2024-01-22 01:49 UTC, MasahiroLittleforest commented on ios-training-komori/View/Weather/FirstViewController.swift
> +        performSegue(withIdentifier: "navigateToWeatherViewController", sender: nil)
ご指摘ありがとうございます。
こちら修正しました！ fd8cb1b

2024-01-22 01:53 UTC, macneko-ayu approved these changes

2024-01-22 02:05 UTC, MasahiroLittleforest commented
レビューありがとうございました。
こちらマージします。

2024-01-22 02:05 UTC, merged